-- ============================================================================
-- Markwise: the finishing migration.
--
-- Everything the app needed but the schema could not yet express:
--
--   1. Marked papers are kept, not thrown away when the tab closes.
--   2. A mock remembers its rubric and which paper number it was drawn from.
--   3. A refused AI call gives the student their allowance back.
--   4. Marking a whole mock is one budgeted call, not one per question.
--   5. Topic mastery carries a spaced-revision schedule.
--   6. Recall practice (flashcards) has somewhere to record itself, kept well
--      away from topic_mastery: mastery is built only from marks awarded
--      against real mark schemes, and a student's own "I knew that" is not
--      that.
--   7. Progress over time, and a per-subject readiness figure.
--
-- Safe to run more than once. Run AFTER 20260915000000_upload_routes.sql.
-- ============================================================================

create extension if not exists pgcrypto;


-- ---------------------------------------------------------------------------
-- 1. A marked paper, kept.
--
-- mark-paper used to assemble a result, hand it to the browser and forget it:
-- a refresh destroyed an hour of marking. The per-question attempts were
-- already written to `attempts`; what was missing was the paper that tied them
-- together.
-- ---------------------------------------------------------------------------

create table if not exists public.paper_attempts (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null default auth.uid() references auth.users (id) on delete cascade,
  paper_id     uuid references public.papers (id) on delete set null,
  subject_code text not null,
  title        text not null,
  awarded      numeric(6,2) not null default 0,
  total        integer not null default 0,
  pct          integer not null default 0,
  grade        text,
  answered     integer not null default 0,
  marked       integer not null default 0,
  unmarkable   integer not null default 0,
  questions    jsonb not null default '[]'::jsonb,
  created_at   timestamptz not null default now()
);

create index if not exists paper_attempts_user_idx
  on public.paper_attempts (user_id, created_at desc);

alter table public.paper_attempts enable row level security;

drop policy if exists "paper_attempts_own" on public.paper_attempts;
create policy "paper_attempts_own" on public.paper_attempts
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);


-- ---------------------------------------------------------------------------
-- 2. Mock additions.
--
-- `instructions` was generated by the mock route on every call and then
-- dropped on the floor. `paper_no` records which paper number the questions
-- were drawn from, so the predicted grade uses the right boundary table
-- instead of whichever paper question 1 happened to come from.
-- ---------------------------------------------------------------------------

alter table public.mocks add column if not exists instructions text;
alter table public.mocks add column if not exists paper_no     integer;


-- ---------------------------------------------------------------------------
-- 3. Give the allowance back when the call failed.
--
-- claim_ai_call reserves before the model runs, which is right: a user out of
-- quota must cost the project nothing. But a 502 from Gemini then charged the
-- student for an answer they never got.
-- ---------------------------------------------------------------------------

create or replace function public.release_ai_call(p_user uuid, p_route text)
returns void
language plpgsql
security definer
set search_path = public
as $fn$
declare
  victim uuid;
begin
  select id into victim
  from public.ai_usage
  where user_id = p_user
    and route = p_route
    and day = (now() at time zone 'utc')::date
  order by created_at desc
  limit 1;

  if victim is not null then
    delete from public.ai_usage where id = victim;
  end if;
end
$fn$;

revoke execute on function public.release_ai_call(uuid, text) from public, anon, authenticated;
grant  execute on function public.release_ai_call(uuid, text) to service_role;


-- ---------------------------------------------------------------------------
-- 4. Daily caps for the routes added since.
--
--   markmock  a whole mock paper marked in batches, one claim for the paper
--   recall    reserved: recall practice costs no AI call today, but the row
--             keeps Settings honest if that ever changes
-- ---------------------------------------------------------------------------

insert into public.ai_limits (route, per_day) values
  ('markmock', 12)
on conflict (route) do nothing;

-- `similar` was capped but never used by any route. Similar-question lookup is
-- pure pgvector and costs no Gemini call, so the cap was meaningless.
delete from public.ai_limits where route = 'similar';


-- ---------------------------------------------------------------------------
-- 5. Spaced revision on top of topic mastery.
--
-- The weakness profile already existed; what it lacked was a clock. These
-- columns hold an SM-2-style schedule per topic, updated by the same trigger
-- that folds a marked answer into mastery, so the schedule maintains itself
-- and the client never has to.
-- ---------------------------------------------------------------------------

alter table public.topic_mastery add column if not exists review_at     date;
alter table public.topic_mastery add column if not exists interval_days integer not null default 0;
alter table public.topic_mastery add column if not exists ease          numeric(4,2) not null default 2.5;
alter table public.topic_mastery add column if not exists last_pct      numeric(5,2);

create index if not exists topic_mastery_review_idx
  on public.topic_mastery (user_id, review_at);

-- Fold a marked answer into mastery AND move the revision schedule.
--
-- The interval grows when the topic is answered well and collapses when it is
-- not, which is the whole point: a topic you keep getting wrong should come
-- back tomorrow, not in three weeks.
create or replace function public.fold_attempt_into_mastery()
returns trigger language plpgsql security definer set search_path = public as $fn$
declare
  this_pct   numeric;
  prev       public.topic_mastery%rowtype;
  next_ease  numeric;
  next_int   integer;
begin
  if new.topic is null or new.total = 0 then
    return new;
  end if;

  this_pct := 100.0 * new.awarded / nullif(new.total, 0);

  select * into prev
  from public.topic_mastery
  where user_id = new.user_id and subject_code = new.subject_code and topic = new.topic;

  -- SM-2, with the five-point quality scale collapsed onto the percentage the
  -- examiner's own mark scheme awarded.
  next_ease := coalesce(prev.ease, 2.5)
             + (0.1 - (100 - this_pct) / 100.0 * (0.28 + (100 - this_pct) / 100.0 * 0.12));
  next_ease := greatest(1.3, least(2.8, next_ease));

  if this_pct < 60 then
    next_int := 1;                                   -- come back tomorrow
  elsif coalesce(prev.interval_days, 0) = 0 then
    next_int := 3;
  elsif prev.interval_days <= 3 then
    next_int := 7;
  else
    next_int := least(120, ceil(prev.interval_days * next_ease)::integer);
  end if;

  insert into public.topic_mastery as m
    (user_id, subject_code, topic, attempts, marks_awarded, marks_total,
     review_at, interval_days, ease, last_pct, updated_at)
  values
    (new.user_id, new.subject_code, new.topic, 1, new.awarded, new.total,
     (current_date + next_int), next_int, next_ease, this_pct, now())
  on conflict (user_id, subject_code, topic) do update
    set attempts      = m.attempts + 1,
        marks_awarded = m.marks_awarded + excluded.marks_awarded,
        marks_total   = m.marks_total + excluded.marks_total,
        review_at     = excluded.review_at,
        interval_days = excluded.interval_days,
        ease          = excluded.ease,
        last_pct      = excluded.last_pct,
        updated_at    = now();
  return new;
end
$fn$;

drop trigger if exists attempts_fold_mastery on public.attempts;
create trigger attempts_fold_mastery
  after insert on public.attempts
  for each row execute function public.fold_attempt_into_mastery();

-- Existing rows predate the schedule: seed one from what is already known so
-- the revision list is not empty for accounts that have been marking for weeks.
update public.topic_mastery
   set review_at = current_date,
       interval_days = 1,
       last_pct = round(100.0 * marks_awarded / nullif(marks_total, 0), 2)
 where review_at is null and marks_total > 0;

-- Topics whose revision has come round, worst first.
create or replace function public.due_revisions(p_subject text default null, p_limit int default 10)
returns table (
  subject_code text, topic text, pct numeric,
  review_at date, days_over integer, interval_days integer, marks_total integer
)
language sql stable security definer set search_path = public as $fn$
  select m.subject_code,
         m.topic,
         round(100.0 * m.marks_awarded / nullif(m.marks_total, 0), 1) as pct,
         m.review_at,
         (current_date - m.review_at)::integer as days_over,
         m.interval_days,
         m.marks_total
  from public.topic_mastery m
  where m.user_id = auth.uid()
    and (p_subject is null or m.subject_code = p_subject)
    and m.review_at is not null
    and m.review_at <= current_date
    and m.marks_total >= 2
  order by (current_date - m.review_at) desc, pct asc nulls last
  limit p_limit;
$fn$;

grant execute on function public.due_revisions to authenticated;


-- ---------------------------------------------------------------------------
-- 6. Recall practice.
--
-- Short real questions, self-rated. Deliberately its own table: topic_mastery
-- is the app's claim that every number it shows came from a real mark scheme,
-- and a student's own "I knew that" must never be allowed to pollute it.
-- ---------------------------------------------------------------------------

create table if not exists public.recall_reviews (
  user_id       uuid not null default auth.uid() references auth.users (id) on delete cascade,
  chunk_id      uuid not null references public.chunks (id) on delete cascade,
  subject_code  text not null,
  reps          integer not null default 0,
  interval_days integer not null default 0,
  ease          numeric(4,2) not null default 2.5,
  due_at        date not null default current_date,
  last_grade    smallint,
  updated_at    timestamptz not null default now(),
  primary key (user_id, chunk_id)
);

create index if not exists recall_due_idx on public.recall_reviews (user_id, subject_code, due_at);

alter table public.recall_reviews enable row level security;
drop policy if exists "recall_own" on public.recall_reviews;
create policy "recall_own" on public.recall_reviews
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- A deck: cards already due first, then cards never seen. Short questions
-- only, and only ones that carry a real mark scheme to reveal.
create or replace function public.recall_deck(
  p_subject text,
  p_limit   int default 15,
  p_max_marks int default 3
)
returns table (
  id uuid, question_no text, paper_code text, marks integer, topic text,
  content text, ms_content text, due_at date, reps integer
)
language sql stable security definer set search_path = public as $fn$
  with mine as (
    select r.chunk_id, r.due_at, r.reps
    from public.recall_reviews r
    where r.user_id = auth.uid() and r.subject_code = p_subject
  )
  select c.id, c.question_no, c.paper_code, c.marks, c.topic,
         c.content, c.ms_content, mine.due_at, coalesce(mine.reps, 0)
  from public.chunks c
  left join mine on mine.chunk_id = c.id
  where c.subject_code = p_subject
    and c.kind = 'question'
    and c.ms_content is not null
    and coalesce(c.marks, 0) between 1 and p_max_marks
    and (mine.chunk_id is null or mine.due_at <= current_date)
  order by (mine.chunk_id is null), mine.due_at asc nulls last, random()
  limit p_limit;
$fn$;

-- Record one self-rating. grade 0 again · 1 hard · 2 good · 3 easy.
create or replace function public.record_recall(
  p_chunk_id uuid,
  p_subject  text,
  p_grade    smallint
) returns void
language plpgsql security definer set search_path = public as $fn$
declare
  prev public.recall_reviews%rowtype;
  next_ease numeric;
  next_int  integer;
begin
  select * into prev
  from public.recall_reviews
  where user_id = auth.uid() and chunk_id = p_chunk_id;

  next_ease := greatest(1.3, least(2.8, coalesce(prev.ease, 2.5) + (p_grade - 2) * 0.13));

  if p_grade = 0 then
    next_int := 1;
  elsif coalesce(prev.reps, 0) = 0 then
    next_int := case when p_grade >= 3 then 4 else 2 end;
  else
    next_int := greatest(1, least(180, ceil(greatest(1, coalesce(prev.interval_days, 1)) * next_ease)::integer));
  end if;

  insert into public.recall_reviews as r
    (user_id, chunk_id, subject_code, reps, interval_days, ease, due_at, last_grade, updated_at)
  values
    (auth.uid(), p_chunk_id, p_subject, 1, next_int, next_ease,
     current_date + next_int, p_grade, now())
  on conflict (user_id, chunk_id) do update
    set reps          = case when p_grade = 0 then 0 else r.reps + 1 end,
        interval_days = excluded.interval_days,
        ease          = excluded.ease,
        due_at        = excluded.due_at,
        last_grade    = excluded.last_grade,
        updated_at    = now();
end
$fn$;

grant execute on function public.recall_deck   to authenticated;
grant execute on function public.record_recall to authenticated;


-- ---------------------------------------------------------------------------
-- 7. Progress over time, and readiness.
-- ---------------------------------------------------------------------------

-- Weekly percentage from real marks. Weeks with no marking are simply absent;
-- drawing a zero for a week the student did not practise would be a lie.
create or replace function public.progress_series(
  p_subject text default null,
  p_weeks   int  default 12
)
returns table (week_start date, awarded numeric, total integer, pct numeric, attempts integer)
language sql stable security definer set search_path = public as $fn$
  select date_trunc('week', a.created_at)::date as week_start,
         sum(a.awarded)::numeric               as awarded,
         sum(a.total)::integer                 as total,
         round(100.0 * sum(a.awarded) / nullif(sum(a.total), 0), 1) as pct,
         count(*)::integer                     as attempts
  from public.attempts a
  where a.user_id = auth.uid()
    and (p_subject is null or a.subject_code = p_subject)
    and a.created_at >= (current_date - (p_weeks * 7))
    and a.total > 0
  group by 1
  order by 1;
$fn$;

-- How ready is this student for this subject?
--
-- Three honest numbers rather than one invented one: how much of the syllabus
-- they have actually been marked on, how well they scored on it, and how
-- recently. The client combines them; the SQL does not pretend to.
create or replace function public.subject_readiness(p_subject text)
returns table (
  topics_total    integer,
  topics_seen     integer,
  topics_strong   integer,
  marks_awarded   numeric,
  marks_total     integer,
  pct             numeric,
  mocks_marked    integer,
  last_activity   timestamptz
)
language sql stable security definer set search_path = public as $fn$
  select
    (select count(distinct c.topic)::integer
       from public.chunks c
      where c.subject_code = p_subject and c.kind = 'question' and c.topic is not null),
    (select count(*)::integer from public.topic_mastery m
      where m.user_id = auth.uid() and m.subject_code = p_subject),
    (select count(*)::integer from public.topic_mastery m
      where m.user_id = auth.uid() and m.subject_code = p_subject
        and m.marks_total > 0 and m.marks_awarded / m.marks_total >= 0.7),
    (select coalesce(sum(a.awarded), 0)::numeric from public.attempts a
      where a.user_id = auth.uid() and a.subject_code = p_subject),
    (select coalesce(sum(a.total), 0)::integer from public.attempts a
      where a.user_id = auth.uid() and a.subject_code = p_subject),
    (select round(100.0 * sum(a.awarded) / nullif(sum(a.total), 0), 1) from public.attempts a
      where a.user_id = auth.uid() and a.subject_code = p_subject),
    (select count(*)::integer from public.mocks k
      where k.user_id = auth.uid() and k.subject_code = p_subject and k.status = 'marked'),
    (select max(a.created_at) from public.attempts a
      where a.user_id = auth.uid() and a.subject_code = p_subject);
$fn$;

grant execute on function public.progress_series   to authenticated;
grant execute on function public.subject_readiness to authenticated;


-- ---------------------------------------------------------------------------
-- 8. Papers a student can practise from, with counts. Powers the Library's
--    paper list without a second round trip per paper.
-- ---------------------------------------------------------------------------

create or replace function public.subject_papers(p_subject text)
returns table (
  paper_id uuid, title text, code text, year integer, session text,
  paper_no integer, variant integer, questions integer, markable integer
)
language sql stable security definer set search_path = public as $fn$
  select p.id, p.title, p.code, p.year, p.session, p.paper_no, p.variant,
         count(c.id) filter (where c.kind = 'question')::integer,
         count(c.id) filter (where c.kind = 'question' and c.ms_content is not null)::integer
  from public.papers p
  left join public.chunks c on c.paper_id = p.id
  where p.subject_code = p_subject and p.kind = 'qp'
  group by p.id
  having count(c.id) filter (where c.kind = 'question') > 0
  order by p.year desc nulls last, p.paper_no, p.variant;
$fn$;

grant execute on function public.subject_papers to authenticated;


do $report$
begin
  raise notice 'Markwise: marked papers are now kept, quota is refundable, revision and recall are scheduled.';
end
$report$;
